export const TEST_API_KEY = "test-api-key-12345"

export const TEST_COMPANY = {
    id: "company-uuid-1",
    name: "TestCompany",
}

export const TEST_APPLICANT_ROW = {
    id: "applicant-uuid-1",
    name: "山田太郎",
    furigana: "やまだたろう",
    email: "yamada@example.com",
    phone: "090-1234-5678",
    address: "大阪府大阪市中央区1-2-3",
    gender: "男性",
    birthDate: new Date("1990-05-15"),
    caseName: "案件A",
    appliedJob: "エンジニア",
    appliedLocation: "大阪府",
    age: 35,
    notes: "テスト備考",
    assigneeName: "担当者A",
    responseStatus: "連絡中",
    connectedAt: new Date("2025-05-20T09:00:00Z"),
    nextActionDate: new Date("2025-06-10"),
    appliedAt: new Date("2025-06-01T10:00:00Z"),
    primaryScheduledDate: new Date("2025-06-15"),
    secScheduledDate: null,
    offered: false,
    joinedDate: null,
    updatedAt: new Date("2025-06-01T10:00:00Z"),
    isValidApplicant: true,
    primaryNoShow: false,
    secNoShow: false,
    finalNoShow: false,
    connectedAt: new Date("2025-05-20T09:00:00Z"),
    primaryScheduled: true,
    secScheduled: false,
    finalScheduled: false,
    primaryConducted: true,
    secConducted: false,
    finalConducted: false,
    docDeclined: false,
    docRejectedMK: false,
    docRejectedClient: false,
    interviewDeclinedBefore: false,
    primaryDeclinedAfter: false,
    primaryRejected: false,
    secDeclinedBefore: false,
    secDeclinedAfter: false,
    secRejected: false,
    finalDeclinedBefore: false,
    finalDeclinedAfter: false,
    finalRejected: false,
    offered: false,
    offerDeclined: false,
    joined: false,
}

export const VALID_INBOUND_PAYLOAD = {
    name: "山田太郎",
    company: "TestCompany",
    job: "エンジニア",
    location: "大阪府",
    email: "yamada@example.com",
    receivedAt: "2025-06-01T10:00:00Z",
    gmailMessageId: "msg-12345",
    threadId: "thread-12345",
}

export const VALID_SYNC_PAYLOAD = {
    companyName: "TestCompany",
    companyCode: "company_001",
    updatedAfter: "",
    cursor: "",
    limit: 200,
}
